# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Applications/CMake 2.8-2.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Applications/CMake 2.8-2.app/Contents/bin/cmake" -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/Applications/CMake 2.8-2.app/Contents/bin/ccmake"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/red/Projects/floatopian-apps/lib/iphone_opencv_test/OpenCV-2.1.0

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/red/Projects/floatopian-apps/lib/iphone_opencv_test

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/Applications/CMake 2.8-2.app/Contents/bin/ccmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/Applications/CMake 2.8-2.app/Contents/bin/cmake" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/Applications/CMake 2.8-2.app/Contents/bin/cmake" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"/Applications/CMake 2.8-2.app/Contents/bin/cmake" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	"/Applications/CMake 2.8-2.app/Contents/bin/cmake" -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\" \"main\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/Applications/CMake 2.8-2.app/Contents/bin/cmake" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/red/Projects/floatopian-apps/lib/iphone_opencv_test/CMakeFiles /Users/red/Projects/floatopian-apps/lib/iphone_opencv_test/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/red/Projects/floatopian-apps/lib/iphone_opencv_test/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named cxcore

# Build rule for target.
cxcore: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cxcore
.PHONY : cxcore

# fast build rule for target.
cxcore/fast:
	$(MAKE) -f src/cxcore/CMakeFiles/cxcore.dir/build.make src/cxcore/CMakeFiles/cxcore.dir/build
.PHONY : cxcore/fast

#=============================================================================
# Target rules for targets named cv

# Build rule for target.
cv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cv
.PHONY : cv

# fast build rule for target.
cv/fast:
	$(MAKE) -f src/cv/CMakeFiles/cv.dir/build.make src/cv/CMakeFiles/cv.dir/build
.PHONY : cv/fast

#=============================================================================
# Target rules for targets named cvaux

# Build rule for target.
cvaux: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cvaux
.PHONY : cvaux

# fast build rule for target.
cvaux/fast:
	$(MAKE) -f src/cvaux/CMakeFiles/cvaux.dir/build.make src/cvaux/CMakeFiles/cvaux.dir/build
.PHONY : cvaux/fast

#=============================================================================
# Target rules for targets named ml

# Build rule for target.
ml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ml
.PHONY : ml

# fast build rule for target.
ml/fast:
	$(MAKE) -f src/ml/CMakeFiles/ml.dir/build.make src/ml/CMakeFiles/ml.dir/build
.PHONY : ml/fast

#=============================================================================
# Target rules for targets named flann

# Build rule for target.
flann: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 flann
.PHONY : flann

# fast build rule for target.
flann/fast:
	$(MAKE) -f 3rdparty/flann/CMakeFiles/flann.dir/build.make 3rdparty/flann/CMakeFiles/flann.dir/build
.PHONY : flann/fast

#=============================================================================
# Target rules for targets named opencv_lapack

# Build rule for target.
opencv_lapack: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opencv_lapack
.PHONY : opencv_lapack

# fast build rule for target.
opencv_lapack/fast:
	$(MAKE) -f 3rdparty/lapack/CMakeFiles/opencv_lapack.dir/build.make 3rdparty/lapack/CMakeFiles/opencv_lapack.dir/build
.PHONY : opencv_lapack/fast

#=============================================================================
# Target rules for targets named zlib

# Build rule for target.
zlib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zlib
.PHONY : zlib

# fast build rule for target.
zlib/fast:
	$(MAKE) -f 3rdparty/zlib/CMakeFiles/zlib.dir/build.make 3rdparty/zlib/CMakeFiles/zlib.dir/build
.PHONY : zlib/fast

#=============================================================================
# Target rules for targets named libjpeg

# Build rule for target.
libjpeg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libjpeg
.PHONY : libjpeg

# fast build rule for target.
libjpeg/fast:
	$(MAKE) -f 3rdparty/libjpeg/CMakeFiles/libjpeg.dir/build.make 3rdparty/libjpeg/CMakeFiles/libjpeg.dir/build
.PHONY : libjpeg/fast

#=============================================================================
# Target rules for targets named libpng

# Build rule for target.
libpng: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 libpng
.PHONY : libpng

# fast build rule for target.
libpng/fast:
	$(MAKE) -f 3rdparty/libpng/CMakeFiles/libpng.dir/build.make 3rdparty/libpng/CMakeFiles/libpng.dir/build
.PHONY : libpng/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... cxcore"
	@echo "... cv"
	@echo "... cvaux"
	@echo "... ml"
	@echo "... flann"
	@echo "... opencv_lapack"
	@echo "... zlib"
	@echo "... libjpeg"
	@echo "... libpng"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

